source 'https://cdn.cocoapods.org'
deployment_target = '15.0'

target 'iosApp' do
    use_frameworks!
    platform :ios, deployment_target
    # Pods for iosApp
    pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '11.13.0'
    pod 'FirebaseAIBridge', :git => 'https://github.com/SeanChinJunKai/FirebaseAIBridge', :branch => 'main'
    pod 'composeApp', :path => '../composeApp'
end

